---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/8/2020 12:58 PM
---

RegisterCommand(vRP.lang.commands.player.emote.stop.cmd, function(source, args, rawCommand)
    vRP.player_stop_animations(source)
end)

RegisterCommand(vRP.lang.commands.player.emote.select.cmd, function(source, args, rawCommand)
    local name = args[1]
    vRP.play_emote(source, name)
end)