---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/8/2020 12:09 PM
---

-- stop the player mission
RegisterCommand(vRP.lang.commands.missions.cancel.cmd, function(source, args, rawCommand)
    vRP.stopMission(source)
end)