---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/8/2020 12:19 PM
---

RegisterCommand(vRP.lang.commands.player.money.give_money.cmd, function(source, args, rawCommand)
    vRP.money_give_to_nearest(source)
end)