---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/8/2020 3:47 PM
---

RegisterCommand(vRP.lang.commands.police.search_register.cmd, function(source, args, rawCommand)
    vRP.police_search_reg(source)
end )

RegisterCommand(vRP.lang.commands.police.show_police_records.cmd, function(source, args, rawCommand)
    vRP.show_police_records(source)
end )

RegisterCommand(vRP.lang.commands.police.delete_police_records.cmd, function(source, args, rawCommand)
    vRP.delete_police_records(source)
end )

RegisterCommand(vRP.lang.commands.police.close_business.cmd, function(source, args, rawCommand)
    vRP.police_close_business(source)
end )
RegisterCommand(vRP.lang.commands.police.track_vehicle.cmd, function(source, args, rawCommand)
    vRP.police_track_vehicle(source)
end )