---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/9/2020 6:24 AM
---

function vRP.player_set_animation_atm_enter(player)
    vRPclient._playAnim(player,false,{{"amb@prop_human_atm@male@enter","enter"},{"amb@prop_human_atm@male@idle_a","idle_a"}},false)
end

function vRP.player_set_animation_atm_exit(player)
    vRPclient._playAnim(player,false,{{"amb@prop_human_atm@male@exit","exit"}},false)
end
