---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/8/2020 10:58 AM
---

-- register a menu builder function
--- name: menu type name
--- builder(add_choices, data) (callback, with custom data table)
---- add_choices(choices) (callback to call once to add the built choices to the menu)
function vRP.registerMenuBuilder(name, builder)
    return error("Menu Builder / vRP Basic Menu was been removed in vRP Infinity")
end
