---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 6/20/2020 8:39 PM
---

-- Resource Metadata
fx_version 'bodacious'
games { 'gta5' }

author 'ImagicTheCat and Muulfz'
description 'A Roleplay Framework'
version '1.0.0'

client_scripts {
    "lib/utils.lua",
    "client/base.lua",
    "client/iplloader.lua",
    "client/gui.lua",
    "client/player_state.lua",
    "client/survival.lua",
    "client/map.lua",
    "client/identity.lua",
    "client/basic_garage.lua",
    "client/police.lua",
    "client/admin.lua"
}

server_scripts{
    "lib/utils.lua",
    "permissions.lua",
    "base.lua",
    "modules/storage/database.lua",
    "modules/gui.lua",
    "modules/group.lua",
    "modules/admin.lua",
    "modules/survival.lua",
    "modules/player_state.lua",
    "modules/map.lua",
    "modules/money.lua",
    "modules/inventory.lua",
    "modules/identity.lua",
    "modules/emotes.lua",
    "modules/police.lua",
    "modules/home.lua",
    "modules/mission.lua",
    "modules/aptitude.lua",

    -- basic implementations
    "modules/cloakroom.lua", --TODO: Create a new cloakroom
    "modules/legacy/basic_menu.lua",
    "modules/commands/*.lua",
    "module/garage.lua",
    "modules/business.lua",
}

ui_page "gui/index.html"

-- client files
files{
    "lib/Tunnel.lua",
    "lib/Proxy.lua",
    "lib/Debug.lua",
    "lib/Luaseq.lua",
    "lib/Tools.lua",
    "cfg/client.lua",
    "gui/index.html",
    "gui/design.css",
    "gui/main.js",
    "gui/Menu.js",
    "gui/ProgressBar.js",
    "gui/WPrompt.js",
    "gui/RequestManager.js",
    "gui/AnnounceManager.js",
    "gui/Div.js",
    "gui/dynamic_classes.js",
}


