---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/7/2020 11:00 PM
---
permissions = {
    player = {
        groups = {
            add = "player.group.add"
        },
        givemoney = "player.givemoney",
        kick = "player.kick",
        coords = "player.coords",
        revive = "player.revive",
        noclip = "player.noclip",
        givemoney = "player.givemoney",
        setmoney = "player.setmoney",
        create_drop = "player.create_drop",
        delete_drop = "player.delete_drop",
        player_list = "player.list"
    },
    admin = {
        whitelist = "player.whitelist",
        group_add = "player.group.add",
        group_remove = "player.group.remove",
        unwhitelist = "player.unwhitelist",
        kick = "player.kick",
        ban = "player.ban",
        unban = "player.unban",
        noclip = "player.noclip",
        custom_emote = "player.custom_emote",
        custom_sound = "player.custom_sound",
        coords = "player.coords",
        teleport_to_me = "player.tptome",
        teleport = "player.tpto",
        givemoney = "player.givemoney",
        giveitem = "player.giveitem",
        display_custom = "player.display_custom",
        calladmin = "player.calladmin"
    }
}
